#!/usr/bin/env bash
echo $ENV_LABEL
export
echo "adding ci pkey"
if [ ! -f ~/.root.useradded ];
then
echo "added ci pkey"
mkdir -p /root/.ssh
echo "
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc1rs3ysOnEqmEKldQN8ilYNyOUFa8XZVC7HHxbJqn1Gze7v0ZnFRn6y6krn+10SHShcCbJgo1uW0mriCzwMcEPJNYGqSBROmqcLI3KY5KXNa2WGG+OP1YClh8SW9m7fBuLT9GwqZLQENgUFdcr+Rd+DoneamTrG/b+ebuupjrCwR1hQH3Msx3GKeRlmJky+fJ6I0AqmfFYIwM89CcwqKUbTuQRb35/U5X+VJVH3Hxa7Zu8wvhn9LTp3grkWGVJbEVlH8vWR/67smAujjEkdm0b8S3jzkNAyX4Dh161AJOl4FC/PddvvYIWZfFl0dl4QkkJqJvRfyouxj2aMOk+TRn runner@ci.kdqugou.com
" > /root/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
touch ~/.root.useradded
fi
echo "gen nginx config"

mkdir -p /opt/etc/nginx_conf_d
echo "

server {
	listen 443 ssl;
    listen   [::]:443 ssl ipv6only=on; ## listen for ipv6

	root /var/www/html/backend/web;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
        server_name _;
        ssl_certificate     /etc/letsencrypt/live/##DOMAIN##/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/##DOMAIN##/privkey.pem;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

	# Make site accessible from http://localhost/
	server_name _;

	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	error_log /dev/stdout info;
	access_log /dev/stdout;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
        location = /404.html {
                root /var/www/errors;
                internal;
        }

        location ^~ /ngd-style.css {
            alias /var/www/errors/style.css;
            access_log off;
        }

        location ^~ /ngd-sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files \$uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off;
    		deny all;
	}

	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6

	root /var/www/html/backend/web;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;

	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	error_log /dev/stdout info;
	access_log /dev/stdout;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
        location = /404.html {
                root /var/www/errors;
                internal;
        }

        location ^~ /ngd-style.css {
            alias /var/www/errors/style.css;
            access_log off;
        }

        location ^~ /ngd-sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files \$uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off;
    		deny all;
	}

	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}


" > /opt/etc/nginx_conf_d/site.conf

cron -f
